# Generated by Django 4.2.10 on 2025-12-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_onboarding_completed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
