# Generated by Django 4.2.10 on 2025-12-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('answers_json', models.JSONField()),
                ('score_vector', models.JSONField(blank=True, null=True)),
                ('personality_traits', models.JSONField(blank=True, null=True)),
                ('skill_levels', models.JSONField(blank=True, null=True)),
                ('interests_vector', models.JSONField(blank=True, null=True)),
                ('completion_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=100)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('alternative_tracks', models.JSONField(blank=True, null=True)),
                ('personalization_factors', models.JSONField(blank=True, null=True)),
                ('feedback_score', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-confidence', '-created_at'],
            },
        ),
    ]
