# Generated by Django 4.2.10 on 2025-12-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('book', 'Book'), ('video', 'Video'), ('course', 'Course'), ('tool', 'Tool'), ('article', 'Article'), ('podcast', 'Podcast'), ('github', 'GitHub Repository')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('estimated_duration_hours', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('subtitles_available', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('skills_covered', models.JSONField(blank=True, default=list)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('broken', 'Broken'), ('deprecated', 'Deprecated'), ('pending_review', 'Pending Review')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_weeks', models.IntegerField(default=12)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('career_tracks', models.JSONField(blank=True, default=list)),
                ('popularity_score', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_order', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.IntegerField(default=20)),
                ('skills_gained', models.JSONField(blank=True, default=list)),
                ('completion_criteria', models.TextField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'roadmap_stages',
                'ordering': ['stage_order'],
                'unique_together': {('roadmap', 'stage_order')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('order_in_stage', models.IntegerField(default=1)),
                ('estimated_completion_days', models.IntegerField(default=3)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_assignments', to='roadmaps.resource')),
                ('roadmap_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.roadmapstage')),
            ],
            options={
                'db_table': 'roadmap_resources',
                'ordering': ['order_in_stage'],
                'unique_together': {('roadmap_stage', 'resource')},
            },
        ),
    ]
