# Generated by Django 4.2.10 on 2025-12-05 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def ensure_created_by_column(apps, schema_editor):
    """
    Ensure created_by column exists with correct name.
    If created_by_id exists, rename it to created_by.
    If created_by exists, do nothing.
    If neither exists, add created_by.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check what columns exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='roadmaps' AND column_name IN ('created_by', 'created_by_id')
        """)
        columns = [row[0] for row in cursor.fetchall()]
        
        if 'created_by' in columns:
            # Column already exists with correct name, do nothing
            return
        elif 'created_by_id' in columns:
            # Rename created_by_id to created_by
            cursor.execute("""
                ALTER TABLE roadmaps 
                RENAME COLUMN created_by_id TO created_by
            """)
        else:
            # Add the column
            cursor.execute("""
                ALTER TABLE roadmaps 
                ADD COLUMN created_by INTEGER REFERENCES users(id) ON DELETE SET NULL
            """)


def reverse_ensure_created_by_column(apps, schema_editor):
    """
    Reverse: rename created_by back to created_by_id if needed
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='roadmaps' AND column_name='created_by'
        """)
        exists = cursor.fetchone()
        
        if exists:
            # Rename back to created_by_id
            cursor.execute("""
                ALTER TABLE roadmaps 
                RENAME COLUMN created_by TO created_by_id
            """)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmaps', '0002_roadmap_is_active_roadmap_track_roadmap_user'),
    ]

    operations = [
        migrations.RunPython(ensure_created_by_column, reverse_ensure_created_by_column),
        migrations.AlterField(
            model_name='roadmap',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
