# Generated by Django 4.2.10 on 2025-12-05 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, null=True)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('calendly_url', models.URLField(blank=True, null=True)),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_mentees', models.IntegerField(default=0)),
                ('response_time_hours', models.IntegerField(default=24)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('mentor_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mentors',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_members', models.IntegerField(default=20)),
                ('current_members', models.IntegerField(default=0)),
                ('meeting_schedule', models.JSONField(blank=True, default=dict)),
                ('discord_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='mentorship.mentor')),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'study_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=50)),
                ('session_type', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('career', 'Career'), ('project_review', 'Project Review')], default='general', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship.mentor')),
            ],
            options={
                'db_table': 'mentoring_sessions',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('contribution_score', models.IntegerField(default=0)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mentorship.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_group_members',
                'ordering': ['-contribution_score', 'joined_at'],
                'unique_together': {('study_group', 'user')},
            },
        ),
    ]
